export const FETCH_MENU_FAILED = "FETCH_MENU_FAILED";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_START = "FETCH_MENU_START";

export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const EDIT_BASKET_ITEM = "EDIT_BASKET_ITEM";
export const PLUS_BASKET_ITEM = "PLUS_BASKET_ITEM";
export const MINUS_BASKET_ITEM = "MINUS_BASKET_ITEM";
export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_FAIL = "PURCHASE_FAIL";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const RESET_PURCHASE_SUCCESS = "RESET_PURCHASE_SUCCESS";

export const INIT_BURGER_INGREDIENTS = "INIT_BURGER_INGREDIENTS";
export const ADD_BURGER_INGREDIENT = "ADD_BURGER_INGREDIENT";
export const REMOVE_BURGER_INGREDIENT = "REMOVE_BURGER_INGREDIENT";
export const ADD_BURGER_ADDITIVE = "ADD_BURGER_ADDITIVE";
export const REMOVE_BURGER_ADDITIVE = "REMOVE_BURGER_ADDITIVE";

export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";