//menuReducer
export const FETCH_MENU_FAILED = "FETCH_MENU_FAILED";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_START = "FETCH_MENU_START";

//basketReducer
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const EDIT_BASKET_ITEM = "EDIT_BASKET_ITEM";
export const PLUS_BASKET_ITEM = "PLUS_BASKET_ITEM";
export const MINUS_BASKET_ITEM = "MINUS_BASKET_ITEM";
export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_FAIL = "PURCHASE_FAIL";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const RESET_PURCHASE_SUCCESS = "RESET_PURCHASE_SUCCESS";

//burgerEditorReducer
export const INIT_BURGER_INGREDIENTS = "INIT_BURGER_INGREDIENTS";
export const ADD_BURGER_INGREDIENT = "ADD_BURGER_INGREDIENT";
export const REMOVE_BURGER_INGREDIENT = "REMOVE_BURGER_INGREDIENT";
export const ADD_BURGER_ADDITIVE = "ADD_BURGER_ADDITIVE";
export const REMOVE_BURGER_ADDITIVE = "REMOVE_BURGER_ADDITIVE";
export const FETCH_INGREDIENTS_START = "FETCH_INGREDIENTS_MENU_START";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGREDIENTS_MENU_FAIL";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_MENU_SUCCESS";

//notificatorReducer
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

//authReducer
export const LOGOUT = "LOGOUT";
export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const RESET_ERRORS = "RESET_ERRORS";
export const SET_IS_MANAGER = "SET_IS_MANAGER";

//userOrdersReducer
export const FETCH_ORDER_LIST_START = "FETCH_ORDER_LIST_START";
export const FETCH_ORDER_LIST_FAIL = "FETCH_ORDER_LIST_FAIL";
export const FETCH_ORDER_LIST_SUCCESS = "FETCH_ORDER_LIST_SUCCESS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const ERASE_ORDERS_LOCALLY = "ERASE_ORDERS_LOCALLY";

//profileReducer
export const PROFILE_LOAD_START = "PROFILE_LOAD_START";
export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS";
export const PROFILE_LOAD_FAIL = "PROFILE_LOAD_FAIL";
export const PROFILE_UPLOAD_START = "PROFILE_UPLOAD_START";
export const PROFILE_UPLOAD_SUCCESS = "PROFILE_UPLOAD_SUCCESS";
export const PROFILE_UPLOAD_FAIL = "PROFILE_UPLOAD_FAIL";
export const PROFILE_ERASE_LOCALLY = "PROFILE_ERASE_LOCALLY";
export const PROFILE_RESET_STATUS = "PROFILE_RESET_STATUS";
export const REAUTH_SHOW = "REAUTH_SHOW";
export const REAUTH_HIDE = "REAUTH_HIDE";
export const SET_PROFILE = "SET_PROFILE";
