export const FETCH_MENU_FAILED = "FETCH_MENU_FAILED";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_START = "FETCH_MENU_START";

export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const PLUS_BASKET_ITEM = "PLUS_BASKET_ITEM";
export const MINUS_BASKET_ITEM = "MINUS_BASKET_ITEM";